*Pandas Session*

In [1]:
import pandas as pd

In [3]:
# step - 1 create df using list

names = ['Ramesh','Suresh','Satish']
names

['Ramesh', 'Suresh', 'Satish']

In [4]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

In [5]:
# pd.DataFrame(data,index,columns)
pd.DataFrame(names)

        0
0  Ramesh
1  Suresh
2  Satish

In [8]:
pd.DataFrame(names,columns = ['Names'])

    Names
0  Ramesh
1  Suresh
2  Satish

In [9]:
pd.DataFrame(names,index=['A','B','C'])

        0
A  Ramesh
B  Suresh
C  Satish

In [11]:
pd.DataFrame(names,index=['A','2','C'],columns = ['Names'])

    Names
A  Ramesh
2  Suresh
C  Satish

In [25]:
# step 2 : two columns
names = ['Ramesh','Satish','Suresh']
ages = [20,24,25]

In [26]:
# combine both of them using ZIP
pd.DataFrame(zip(names,ages),columns = ['Names','Age'])

    Names  Age
0  Ramesh   20
1  Satish   24
2  Suresh   25

In [27]:
names = ['Ramesh','Satish','Suresh']
ages = [20,24,25]
place = ['Mumbai','Pune','Banglore']

In [28]:
pd.DataFrame(zip(names,ages,place),columns = ['Names','Age','Place'])

    Names  Age     Place
0  Ramesh   20    Mumbai
1  Satish   24      Pune
2  Suresh   25  Banglore

In [29]:
# step 3 : create a df using dictionary

d = {'Names' : ['Ramesh','Satish','Suresh'],
    'Age' : [20,24,25]}
d

{'Names': ['Ramesh', 'Satish', 'Suresh'], 'Age': [20, 24, 25]}

In [40]:
pd.DataFrame(d)

    Names  Age
0  Ramesh   20
1  Satish   24
2  Suresh   25

In [41]:
pd.DataFrame(d, columns = ['Age'])

   Age
0   20
1   24
2   25

In [43]:
# step 4 : Selection updation and add column 
# select the column
# update the column
# add the column

In [55]:
d = {'Names' : ['Ramesh','Satish','Suresh'],
    'Age' : [20,24,25]}
df  = pd.DataFrame(d)
df

    Names  Age
0  Ramesh   20
1  Satish   24
2  Suresh   25

In [57]:
# select the column
df['Names']

0    Ramesh
1    Satish
2    Suresh
Name: Names, dtype: str

In [58]:
df['Name']

KeyError: 'Name'

In [59]:
# update the column
df['Age'] = [30,34,45]

In [60]:
df

    Names  Age
0  Ramesh   30
1  Satish   34
2  Suresh   45

In [61]:
# add the column
df['City'] = ['Hyd','Mum','Pune']
df

    Names  Age  City
0  Ramesh   30   Hyd
1  Satish   34   Mum
2  Suresh   45  Pune

In [62]:
df.insert(0, 'Sequence', range(1, len(df) + 1))

In [63]:
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Suresh   45  Pune

In [65]:
dir(df)

['Age',
 'City',
 'Names',
 'Sequence',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [67]:
df.values

array([[1, 'Ramesh', 30, 'Hyd'],
       [2, 'Satish', 34, 'Mum'],
       [3, 'Suresh', 45, 'Pune']], dtype=object)

In [68]:
df.sort_values()

<bound method DataFrame.sort_values of    Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Suresh   45  Pune>

In [69]:
df.replace('Suresh','Mahesh')

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   45  Pune

In [70]:
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Suresh   45  Pune

In [72]:
df.replace('Suresh','Mahesh',inplace = True) # by default inplace value is flase so if we make changes it will not affect on original data frame so we have to make Inplace as True

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   45  Pune

In [76]:
#condition 
import numpy as np
np.where(df['Names']=='Mahesh')

(array([2]),)

In [77]:
df['Names']=='Mahesh'

0    False
1    False
2     True
Name: Names, dtype: bool

In [80]:
l = [] 
for i,j in zip(df['Names'],df['Age']) :
    if i == 'Mahesh' :
            l.append(45)
    else :
            l.append(j)
df['Age'] = l

In [81]:
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   45  Pune

In [84]:
import numpy as np
df['Age'] = np.where(df['Names'] == 'Mahesh',65,df['Age'])
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   65  Pune

In [86]:
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   65  Pune

In [88]:
# how to drop a column
# df.drop(labels,axis,index,columns)
# df.drop === i can drop column, i can drop index
# labels == either column or index 
# df.drop('city')  # this city might be index or might be column
# axis = 0 then then it will be index
# axis = 1 then it will be column
# by default axis = 0

In [93]:
df.drop('City') # drop index name city

KeyError: "['City'] not found in axis"

In [94]:
df.drop('City',axis = 1) # drop column name city

   Sequence   Names  Age
0         1  Ramesh   30
1         2  Satish   34
2         3  Mahesh   65

In [95]:
df

   Sequence   Names  Age  City
0         1  Ramesh   30   Hyd
1         2  Satish   34   Mum
2         3  Mahesh   65  Pune

In [96]:
df.drop('City',axis = 1, inplace = True) # drop column name city with inplace to update the list

In [97]:
df

   Sequence   Names  Age
0         1  Ramesh   30
1         2  Satish   34
2         3  Mahesh   65

In [98]:
df

   Sequence   Names  Age
0         1  Ramesh   30
1         2  Satish   34
2         3  Mahesh   65

In [101]:
df.drop(df.columns[0], axis=1)

    Names  Age
0  Ramesh   30
1  Satish   34
2  Mahesh   65

In [103]:
df

   Sequence   Names  Age
0         1  Ramesh   30
1         2  Satish   34
2         3  Mahesh   65

In [106]:
df.drop(columns=['Age'])

   Sequence   Names
0         1  Ramesh
1         2  Satish
2         3  Mahesh